### ISSUE TITLE
Liquid Exception: undefined method `to_date' for Liquid::Utils:Module in _pages/tags.html

### ISSUE THREAD

**Issue by copolii** [artemsheludko/adam-blog#3]
I'm not able to build/serve this theme (I haven't made any changes) with Jekyll. I'd try to fix it myself and send a pull request, but I've never even touched Ruby before, so it might take a while. I hope the information below is helpful.

```
user@MACHINE:~/Documents/adam-blog$ jekyll build --trace
Configuration file: /home/user/Documents/adam-blog/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /home/user/Documents/adam-blog
       Destination: /home/user/Documents/adam-blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: undefined method `to_date' for Liquid::Utils:Module in _pages/tags.html
/var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/filters.rb:362:in `time': undefined method `to_date' for Liquid::Utils:Module (NoMethodError)
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/filters.rb:76:in `date_to_string'
	from /usr/lib/ruby/vendor_ruby/liquid/strainer.rb:51:in `invoke'
	from /usr/lib/ruby/vendor_ruby/liquid/context.rb:95:in `invoke'
	from /usr/lib/ruby/vendor_ruby/liquid/variable.rb:88:in `block in render'
	from /usr/lib/ruby/vendor_ruby/liquid/variable.rb:86:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/variable.rb:86:in `inject'
	from /usr/lib/ruby/vendor_ruby/liquid/variable.rb:86:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:151:in `render_token'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:135:in `block in render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/if.rb:39:in `block (2 levels) in render'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/if.rb:37:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/if.rb:37:in `block in render'
	from /usr/lib/ruby/vendor_ruby/liquid/context.rb:132:in `stack'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/if.rb:36:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:151:in `render_token'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:135:in `block in render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:113:in `block (2 levels) in render'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:100:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:100:in `each_with_index'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:100:in `block in render'
	from /usr/lib/ruby/vendor_ruby/liquid/context.rb:132:in `stack'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:99:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:151:in `render_token'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:135:in `block in render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/unless.rb:15:in `block in render'
	from /usr/lib/ruby/vendor_ruby/liquid/context.rb:132:in `stack'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/unless.rb:10:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:151:in `render_token'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:135:in `block in render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:113:in `block (2 levels) in render'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:100:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:100:in `each_with_index'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:100:in `block in render'
	from /usr/lib/ruby/vendor_ruby/liquid/context.rb:132:in `stack'
	from /usr/lib/ruby/vendor_ruby/liquid/tags/for.rb:99:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:151:in `render_token'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:135:in `block in render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `each'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `render_all'
	from /usr/lib/ruby/vendor_ruby/liquid/block.rb:108:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/template.rb:210:in `block in render'
	from /usr/lib/ruby/vendor_ruby/liquid/template.rb:262:in `with_profiling'
	from /usr/lib/ruby/vendor_ruby/liquid/template.rb:209:in `render'
	from /usr/lib/ruby/vendor_ruby/liquid/template.rb:222:in `render!'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:123:in `render_liquid'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:76:in `render_document'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:466:in `block in render_pages'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `each'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `render_pages'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:193:in `render'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```
Here's a list of my local installed gems:
```
addressable (2.5.2)
afm (0.2.2)
Ascii85 (1.0.2)
bigdecimal (1.3.2, 1.2.8)
blankslate (3.1.3)
bundler (1.16.0)
classifier-reborn (2.1.0, 2.0.4)
coderay (1.1.2, 1.1.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2, 1.10.0)
colorator (1.1.0)
connection_pool (2.2.1)
did_you_mean (1.0.0)
execjs (2.7.0, 2.6.0)
fast-stemmer (1.0.2)
ffi (1.9.18, 1.9.10)
forwardable-extended (2.6.0)
hashery (2.1.2)
io-console (0.4.6, 0.4.5)
jekyll (3.6.2)
jekyll-feed (0.9.2)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.5.0)
jekyll-seo-tag (2.3.0)
jekyll-sitemap (1.1.1)
jekyll-watch (1.5.0)
json (2.1.0, 1.8.3)
kramdown (1.15.0, 1.14.0)
launchy (2.4.3, 2.3.0)
liquid (4.0.0, 3.0.6)
listen (3.1.5, 3.0.8, 3.0.3)
mercenary (0.3.6, 0.3.5)
mime-types (3.1)
mime-types-data (3.2016.0521, 3.2015.1120)
minima (2.1.1)
minitest (5.10.3)
molinillo (0.6.4, 0.5.0)
multi_json (1.12.2, 1.12.1)
net-http-persistent (3.0.0, 2.9.4)
net-telnet (0.1.1)
oj (3.3.9, 2.17.4)
parslet (1.8.0, 1.7.1)
pathutil (0.16.0)
pdf-core (0.7.0, 0.6.1)
pdf-reader (2.0.0, 1.4.0)
pg (0.18.4)
posix-spawn (0.3.13, 0.3.11)
power_assert (1.1.1, 0.2.7)
prawn (2.2.2, 2.1.0)
prawn-table (0.2.2)
psych (2.2.4, 2.1.0)
public_suffix (3.0.0)
pygments.rb (1.2.0, 0.6.3)
rake (12.2.1, 12.0.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10, 0.9.7)
rdiscount (2.2.0.1, 2.1.8)
rdoc (5.1.0, 4.2.1)
redcarpet (3.4.0)
rouge (3.0.0, 2.2.1, 2.0.2)
ruby-rc4 (0.1.5)
ruby_dep (1.5.0)
safe_yaml (1.0.4)
sass (3.5.3, 3.4.23)
sass-listen (4.0.0)
sequel (5.2.0, 4.37.0)
sequel_pg (1.6.16)
stringex (2.7.1, 2.6.1)
test-unit (3.2.6, 3.2.5)
thor (0.20.0, 0.19.4)
toml (0.1.2)
ttfunk (1.5.1, 1.4.0)
yajl-ruby (1.3.0, 1.2.0)
```

**Comment by copolii** [comment]
Closing this issue: After further research, it looks like Ubuntu had installed an older version of the `liquid` library (3.0.6) and even though I had the right version (4.0.0) installed through `gem`, Ubuntu's library somehow got priority.

**Comment by ghost** [comment]
This was so damn helpful. Coming from a pure debian build and installing ruby-full, liquid and jekyll both had to be removed and then it just worked.
